#cloud-config

apt_update: true
packages:
  - unzip
  - apache2
  - mariadb-server
  - mariadb-client
  - php
  - libapache2-mod-php
  - php-cli
  - php-fpm
  - php-json
  - php-common
  - php-mysql
  - php-zip
  - php-gd
  - php-intl
  - php-mbstring
  - php-curl
  - php-xml
  - php-pear
  - php-tidy
  - php-soap
  - php-bcmath
  - php-xmlrpc
  - php-uploadprogress
  - php-apcu
runcmd:
  - [ mkdir, /run/cloud-config-drupal ]
  - [ mkdir, /run/cloud-config-drupal/install ]
  - [ cd, /run/cloud-config-drupal/install ]
  - [ wget, https://raw.githubusercontent.com/agcraggs/multipass-cloud-init-drupal/main/install.sh ]
  - [ sh, install.sh ]
# Must escape commands with ,
#  - [  ]
